name: Baseball Season Highs Check
'on':
  schedule:
  - cron: 0 12 15 2 *
  - cron: 0 12 16 2 *
  - cron: 0 12 17 2 *
  - cron: 0 12 22 2 *
  - cron: 0 12 23 2 *
  - cron: 0 12 24 2 *
  - cron: 0 12 2 3 *
  - cron: 0 12 3 3 *
  - cron: 0 12 6 3 *
  - cron: 0 12 7 3 *
  - cron: 0 12 8 3 *
  - cron: 0 12 9 3 *
  - cron: 0 12 15 3 *
  - cron: 0 12 16 3 *
  - cron: 0 12 17 3 *
  - cron: 0 12 22 3 *
  - cron: 0 12 23 3 *
  - cron: 0 12 24 3 *
  - cron: 0 12 29 3 *
  - cron: 0 12 30 3 *
  - cron: 0 12 31 3 *
  - cron: 0 12 5 4 *
  - cron: 0 12 6 4 *
  - cron: 0 12 7 4 *
  - cron: 0 12 12 4 *
  - cron: 0 12 13 4 *
  - cron: 0 12 14 4 *
  - cron: 0 12 16 4 *
  - cron: 0 12 18 4 *
  - cron: 0 12 19 4 *
  - cron: 0 12 20 4 *
  - cron: 0 12 26 4 *
  - cron: 0 12 27 4 *
  - cron: 0 12 28 4 *
  - cron: 0 12 2 5 *
  - cron: 0 12 3 5 *
  - cron: 0 12 9 5 *
  - cron: 0 12 10 5 *
  - cron: 0 12 11 5 *
  - cron: 0 12 12 5 *
  - cron: 0 12 16 5 *
  - cron: 0 12 24 5 *
  - cron: 0 12 1 6 *
  workflow_dispatch: null
jobs:
  check-season-highs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt'
    - name: Check for new season highs
      run: python main.py -sport baseball
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
